### ISSUE TITLE
Please add run requirement: curl

### ISSUE THREAD

**Issue by huubknops** [leiweibau/Pi.Alert-Satellite#1]
Please add run requirement curl to installation: apt-get install curl

With clean debian install, curl is not available. For external internet IP recognition "curl" is required and first scan crashes.

# uname -a
Linux satellite1 6.5.13-1-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.13-1 (2024-02-05T13:50Z) x86_64 GNU/Linux

**Comment by leiweibau** [comment]
Thanks for the tip. I will correct that.

And a big thank you for the sponsorship 🙏
